FROM centos
# update
RUN yum update -y \
&& yum install git -y
# install helm
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
&& chmod 700 get_helm.sh \
&& ./get_helm.sh

RUN groupadd -g 1000 jenkins \
&& useradd -u 1000 -g 1000 -G wheel jenkins

USER jenkins